package  {	import com.thanksmister.touchlist.renderers.TouchListItemRenderer;	import flash.display.Bitmap;	import flash.display.BitmapData;	import flash.events.Event;	import flash.display.MovieClip;	public class MyTouchListItemRenderer extends TouchListItemRenderer{		var bitmap:Bitmap;		var _artist:String;		var _songname:String;		var _coverpath:String;		public function MyTouchListItemRenderer(songname:String , artistname:String ,coverpath:String) {			// constructor code			bitmap = new Bitmap(new BitmapData(720,135,false ,0xFFFFFF));			bitmap.smoothing = true;			addChild(bitmap);			super();			_artist = artistname;			_songname = songname;						var stringStart:Number = 0;			var stringEnd:Number = coverpath.lastIndexOf(".") ;			_coverpath = coverpath.slice(stringStart,stringEnd)+"_thumb"+coverpath.slice(stringEnd,coverpath.length);			var cover:SmoothingBitmapLoader = new SmoothingBitmapLoader(_coverpath);			cover.addEventListener(SmoothingBitmapLoader.INIT,onLoaded);			addEventListener(Event.REMOVED_FROM_STAGE,function onRemoved(e:Event)
			{
				removeEventListener(Event.REMOVED_FROM_STAGE, onRemoved);
				try{
					bitmap.bitmapData.dispose();
				}
				catch(e:*)
				{
					trace("MyTouchListItemRenderer "+e.toString());
				}
			});					}		function onLoaded(e:Event)		{			e.target.removeEventListener(SmoothingBitmapLoader.INIT,onLoaded);			var mc:Bitmap = e.target.loaderContent as Bitmap;			bitmap.bitmapData.draw(mc);		}		public function drawListItem(l:SmoothingBitmapLoader)		{			//e.target.removeEventListener(SmoothingBitmapLoader.INIT,onLoaded);//			var l:SmoothingBitmapLoader = e.target as SmoothingBitmapLoader;						var mc:MovieClip = l.loaderContent as MovieClip;			mc.songname_tf.text = _songname;			mc.artist_tf.text = _artist;			//trace("onLoaded");			bitmap.bitmapData.draw(l);			this.draw();			//removeChild(bitmap);								}		override protected function draw():void		{			if(!initialized) return 													this.graphics.clear();						this.graphics.beginFill(0x000000, 1);			this.graphics.drawRect(0, 0, itemWidth, itemHeight);			this.graphics.endFill();						this.graphics.beginFill(0xEAEAEA, .5);			this.graphics.drawRect(0, itemHeight - 1, itemWidth, .5);			this.graphics.endFill();			graphics.beginBitmapFill(bitmap.bitmapData);			this.filters = [];		}					}	}